### PR TITLE
Update some tests for pygfx 0.3.0 compatibility

### PR DESCRIPTION
**Pull request by hmaarrfk**
i got the constants by adding print statements.

### CODE REVIEW

**Comment by almarklein** [comment]
Thanks! At some point I got lazy making it backwards compatible :P

**Comment by hmaarrfk** [comment]
my laptop is too wimpy to run your benchmarks....

**Comment by almarklein** [comment]
which ones? The 2D and 3D texture sizes can be configured, maybe that helps.

**Comment by hmaarrfk** [comment]
I'll look into it after hours.

It might be that i have an intel IGPU and 16GB of RAM. I thought 16GB would be plenty, but maybe not... I don't really understand what the "graphics buffer" means in the bios configuration. I feel like many of my applications use textures that are often 2-3GB in size on the IGPU......

**Pull request merged**
